import { useEffect,useMemo,useState } from 'react';
import { Check,Clock3,FileCheck2,RefreshCw,UserX } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { listEvents } from '../services/events';
import { useLanguage } from '../i18n';
import './attendance.css';

const copy={
 es:{control:'Control del entrenador',title:'Asistencia',intro:'Selecciona una sesión y marca el estado de cada nadador.',sessions:'Sesiones',noTrainings:'No hay entrenamientos creados.',selected:'Sesión seleccionada',loading:'Cargando asistencia…',select:'Selecciona una sesión.',unmarked:'Sin marcar',counts:{present:'presentes',late:'tarde',justified:'justificadas',unjustified:'no justificadas'},status:{present:'Presente',late:'Tarde',justified:'Justificada',unjustified:'No justificada'}},
 ca:{control:"Control de l'entrenador",title:'Assistència',intro:'Selecciona una sessió i marca l’estat de cada nedador.',sessions:'Sessions',noTrainings:'No hi ha entrenaments creats.',selected:'Sessió seleccionada',loading:'Carregant assistència…',select:'Selecciona una sessió.',unmarked:'Sense marcar',counts:{present:'presents',late:'tard',justified:'justificades',unjustified:'no justificades'},status:{present:'Present',late:'Tard',justified:'Justificada',unjustified:'No justificada'}}
};

export default function AttendancePage({user}){
  const{language,t}=useLanguage();const c=copy[language];const locale=language==='ca'?'ca-ES':'es-ES';
  const statuses={present:{label:c.status.present,icon:Check},late:{label:c.status.late,icon:Clock3},justified:{label:c.status.justified,icon:FileCheck2},unjustified:{label:c.status.unjustified,icon:UserX}};
  const[events,setEvents]=useState([]);const[athletes,setAthletes]=useState([]);const[attendance,setAttendance]=useState({});const[selected,setSelected]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState('');const[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const [ev,{data:profiles,error:pErr}]=await Promise.all([listEvents(),supabase.from('profiles').select('id,full_name,active').eq('role','athlete').eq('active',true).order('full_name')]);if(pErr)throw pErr;const training=ev.filter(x=>x.type==='training').sort((a,b)=>b.event_date.localeCompare(a.event_date)||String(b.start_time).localeCompare(String(a.start_time)));setEvents(training);setAthletes(profiles||[]);const target=selected||training[0]?.id||'';setSelected(target);if(target)await loadAttendance(target)}catch(e){setError(e.message)}finally{setLoading(false)}};
  const loadAttendance=async eventId=>{const{data,error:e}=await supabase.from('attendance').select('*').eq('event_id',eventId);if(e)throw e;const map={};(data||[]).forEach(x=>map[x.athlete_id]=x);setAttendance(map)};
  useEffect(()=>{load()},[]);
  const chooseEvent=async id=>{setSelected(id);setLoading(true);setError('');try{await loadAttendance(id)}catch(e){setError(e.message)}finally{setLoading(false)}};
  const setStatus=async(athleteId,status)=>{if(!selected)return;setSaving(athleteId);setError('');const previous=attendance[athleteId];setAttendance(prev=>({...prev,[athleteId]:{...(prev[athleteId]||{}),event_id:selected,athlete_id:athleteId,status}}));const payload={event_id:selected,athlete_id:athleteId,status,validated_by:user.id,updated_at:new Date().toISOString()};const{data,error:e}=await supabase.from('attendance').upsert(payload,{onConflict:'event_id,athlete_id'}).select().single();if(e){setError(e.message);setAttendance(prev=>{const n={...prev};if(previous)n[athleteId]=previous;else delete n[athleteId];return n})}else setAttendance(prev=>({...prev,[athleteId]:data}));setSaving('')};
  const activeEvent=events.find(x=>x.id===selected);const counts=useMemo(()=>Object.values(attendance).reduce((a,x)=>{if(x?.status)a[x.status]=(a[x.status]||0)+1;return a},{present:0,late:0,justified:0,unjustified:0}),[attendance]);
  return <section className="attendance-page"><div className="section-toolbar"><div><span className="eyebrow">{c.control}</span><h2>{c.title}</h2><p>{c.intro}</p></div><button className="inline-action" onClick={load}><RefreshCw size={17}/>{t.common.update}</button></div>{error&&<div className="error">{error}</div>}<div className="attendance-layout"><aside className="attendance-sessions card"><h3>{c.sessions}</h3>{events.length===0?<p className="empty-state">{c.noTrainings}</p>:events.map(ev=><button key={ev.id} className={selected===ev.id?'active':''} onClick={()=>chooseEvent(ev.id)}><strong>{new Date(`${ev.event_date}T12:00:00`).toLocaleDateString(locale,{day:'2-digit',month:'short'})}</strong><span>{ev.start_time?.slice(0,5)}–{ev.end_time?.slice(0,5)}</span>{ev.place&&<small>{ev.place}</small>}</button>)}</aside><div className="attendance-main">{activeEvent&&<section className="attendance-summary card"><div><span className="eyebrow">{c.selected}</span><h3>{new Date(`${activeEvent.event_date}T12:00:00`).toLocaleDateString(locale,{weekday:'long',day:'numeric',month:'long'})}</h3><p>{activeEvent.start_time?.slice(0,5)}–{activeEvent.end_time?.slice(0,5)}{activeEvent.place?` · ${activeEvent.place}`:''}</p></div><div className="attendance-counts"><span className="present">{counts.present} {c.counts.present}</span><span className="late">{counts.late} {c.counts.late}</span><span className="justified">{counts.justified} {c.counts.justified}</span><span className="unjustified">{counts.unjustified} {c.counts.unjustified}</span></div></section>}{loading?<section className="card">{c.loading}</section>:!selected?<section className="card empty-state">{c.select}</section>:<div className="athlete-attendance-list">{athletes.map(a=>{const current=attendance[a.id]?.status;return <article className="card athlete-attendance" key={a.id}><div className="athlete-name"><div className="avatar-mini">{(a.full_name||'?').trim().charAt(0).toUpperCase()}</div><div><strong>{a.full_name}</strong><span>{current?statuses[current].label:c.unmarked}</span></div></div><div className="status-buttons">{Object.entries(statuses).map(([key,item])=>{const Icon=item.icon;return <button key={key} disabled={saving===a.id} className={`${key} ${current===key?'selected':''}`} onClick={()=>setStatus(a.id,key)}><Icon size={16}/><span>{item.label}</span></button>})}</div></article>})}</div>}</div></div></section>;
}
