import { useEffect,useMemo,useState } from 'react';
import { ChevronLeft,ChevronRight,X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { listEvents } from '../services/events';
import { useLanguage } from '../i18n';
import './CalendarPage.css';
const isoDate=(y,m,d)=>`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
const startOffset=date=>date.getDay()===0?6:date.getDay()-1;
const localToday=()=>new Date().toLocaleDateString('en-CA');
const copy={es:{shared:'Calendario compartido',intro:'Entrenamientos y competiciones del programa.',today:'Hoy',previous:'Mes anterior',next:'Mes siguiente',loading:'Cargando calendario…',training:'Entrenamiento',competition:'Competición',selected:'Día seleccionado',close:'Cerrar selección',noEvents:'No hay eventos este día.',noTime:'Sin hora',months:['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],week:['Lun','Mar','Mié','Jue','Vie','Sáb','Dom']},ca:{shared:'Calendari compartit',intro:'Entrenaments i competicions del programa.',today:'Avui',previous:'Mes anterior',next:'Mes següent',loading:'Carregant calendari…',training:'Entrenament',competition:'Competició',selected:'Dia seleccionat',close:'Tancar selecció',noEvents:'No hi ha esdeveniments aquest dia.',noTime:'Sense hora',months:['gener','febrer','març','abril','maig','juny','juliol','agost','setembre','octubre','novembre','desembre'],week:['Dl','Dt','Dc','Dj','Dv','Ds','Dg']}};
export default function CalendarPage(){const{language}=useLanguage();const c=copy[language];const locale=language==='ca'?'ca-ES':'es-ES';const[cursor,setCursor]=useState(()=>new Date());const[events,setEvents]=useState([]);const[selected,setSelected]=useState(localToday());const[loading,setLoading]=useState(true);const[error,setError]=useState('');const navigate=useNavigate();
useEffect(()=>{(async()=>{try{setLoading(true);setEvents(await listEvents())}catch(e){setError(e.message)}finally{setLoading(false)}})()},[]);
const cells=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),days=new Date(y,m+1,0).getDate(),lead=startOffset(new Date(y,m,1)),total=Math.ceil((lead+days)/7)*7;return Array.from({length:total},(_,i)=>{const d=i-lead+1;return d>=1&&d<=days?{day:d,date:isoDate(y,m,d)}:null})},[cursor]);
const byDate=useMemo(()=>events.reduce((a,e)=>{(a[e.event_date]??=[]).push(e);return a},{}),[events]);const selectedEvents=byDate[selected]||[];const go=e=>navigate(e.type==='training'?'/sessions':'/competitions');const choose=date=>setSelected(date);const prev=()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1));const next=()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1));const today=()=>{const n=new Date();setCursor(n);setSelected(localToday())};
return <section className="calendar-wrap"><div className="section-toolbar"><div><span className="eyebrow">{c.shared}</span><h2>{c.months[cursor.getMonth()]} {cursor.getFullYear()}</h2><p>{c.intro}</p></div><div className="toolbar-actions"><button onClick={prev} aria-label={c.previous}><ChevronLeft size={18}/></button><button onClick={today}>{c.today}</button><button onClick={next} aria-label={c.next}><ChevronRight size={18}/></button></div></div>{error&&<div className="error">{error}</div>}{loading?<div className="card">{c.loading}</div>:<><div className="calendar-card"><div className="calendar-head">{c.week.map(d=><div key={d}>{d}</div>)}</div><div className="calendar-grid">{cells.map((cell,i)=><div onClick={()=>cell&&choose(cell.date)} className={`calendar-cell ${!cell?'empty':''} ${cell?.date===localToday()?'today':''} ${cell?.date===selected?'selected':''}`} key={i}>{cell&&<><span className="day-number">{cell.day}</span><div className="day-events">{(byDate[cell.date]||[]).slice(0,3).map(e=><button onClick={x=>{x.stopPropagation();choose(cell.date);go(e)}} key={e.id} className={`calendar-event ${e.type}`}><strong>{e.type==='training'?c.training:c.competition}</strong><span>{e.start_time?.slice(0,5)||''}{e.place?` · ${e.place}`:''}</span></button>)}{(byDate[cell.date]||[]).length>3&&<span className="calendar-event-more">+{byDate[cell.date].length-3}</span>}</div></>}</div>)}</div></div><div className="calendar-legend"><span><i className="dot training"/>{c.training}</span><span><i className="dot competition"/>{c.competition}</span></div><section className="card mobile-day-panel"><div className="day-panel-head"><div><span className="eyebrow">{c.selected}</span><h3>{new Date(`${selected}T12:00:00`).toLocaleDateString(locale,{weekday:'long',day:'numeric',month:'long'})}</h3></div>{selected!==localToday()&&<button onClick={()=>setSelected(localToday())} aria-label={c.close}><X size={18}/></button>}</div>{selectedEvents.length?<div className="day-panel-list">{selectedEvents.map(e=><button className={`day-panel-event ${e.type}`} key={e.id} onClick={()=>go(e)}><i className="event-dot"/><div><b>{e.type==='training'?c.training:c.competition}</b><span>{e.start_time?.slice(0,5)||c.noTime}{e.place?` · ${e.place}`:''}{e.planned_meters?` · ${e.planned_meters} m`:''}</span></div><ChevronRight size={18}/></button>)}</div>:<p className="day-panel-empty">{c.noEvents}</p>}</section></>}</section>}
