import { useEffect,useState } from 'react';
import { CalendarDays,CheckCircle2,Clock3,MapPin,Plus,Ruler,Waves,X } from 'lucide-react';
import { createTraining,listEvents } from '../services/events';
import { supabase } from '../lib/supabase';
import { useLanguage } from '../i18n';
import './SessionsPage.css';
const emptyForm={event_date:'',start_time:'',end_time:'',place:'',planned_meters:'',description:''};
const finished=e=>{const end=e.end_time||'23:59';return new Date()>=new Date(`${e.event_date}T${end}`)};
export default function SessionsPage({user}){const{t,language}=useLanguage();const s=t.sessions;const locale=language==='ca'?'ca-ES':'es-ES';const[events,setEvents]=useState([]);const[responses,setResponses]=useState({});const[form,setForm]=useState(emptyForm);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[answering,setAnswering]=useState(null);const[answer,setAnswer]=useState({borg:5,meters:'',comment:''});
async function refresh(){try{setLoading(true);setError('');const ev=(await listEvents()).filter(e=>e.type==='training').sort((a,b)=>b.event_date.localeCompare(a.event_date));setEvents(ev);let q=supabase.from('training_responses').select('*');if(user.role==='athlete')q=q.eq('athlete_id',user.id);const{data,error:e}=await q;if(e)throw e;const map={};(data||[]).forEach(r=>{if(user.role==='athlete')map[r.event_id]=r;else(map[r.event_id]??=[]).push(r)});setResponses(map)}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{refresh()},[user.id,user.role]);
async function submit(e){e.preventDefault();try{setSaving(true);setError('');await createTraining(form,user.id);setForm(emptyForm);setOpen(false);await refresh()}catch(e){setError(e.message)}finally{setSaving(false)}}
async function sendResponse(e,event){e.preventDefault();try{setSaving(true);setError('');const start=new Date(`${event.event_date}T${event.start_time}`),end=new Date(`${event.event_date}T${event.end_time}`);const duration=Math.max(0,Math.round((end-start)/60000));const{error:e2}=await supabase.from('training_responses').insert({event_id:event.id,athlete_id:user.id,borg:+answer.borg,meters:+answer.meters,duration_minutes:duration,comment:answer.comment.trim()||null});if(e2)throw e2;setAnswering(null);setAnswer({borg:5,meters:'',comment:''});await refresh()}catch(e){setError(e.code==='23505'?s.duplicate:e.message)}finally{setSaving(false)}}
const sessionForm=<form className="session-sheet" onSubmit={submit}><div className="session-sheet-head"><div><span className="eyebrow light">{s.new}</span><h3>{s.training}</h3><p>{s.newText}</p></div><button type="button" className="sheet-close" onClick={()=>setOpen(false)} aria-label={t.nav.close}><X size={22}/></button></div><div className="session-sheet-body"><label className="field-card"><span><CalendarDays size={18}/>{s.date}</span><input type="date" required value={form.event_date} onChange={e=>setForm({...form,event_date:e.target.value})}/></label><div className="time-row"><label className="field-card"><span><Clock3 size={18}/>{s.start}</span><input type="time" required value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/></label><label className="field-card"><span><Clock3 size={18}/>{s.end}</span><input type="time" required value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></label></div><label className="field-card"><span><MapPin size={18}/>{s.place}</span><input value={form.place} onChange={e=>setForm({...form,place:e.target.value})} placeholder={s.placePlaceholder}/></label><label className="field-card"><span><Ruler size={18}/>{s.planned}</span><input type="number" min="0" inputMode="numeric" value={form.planned_meters} onChange={e=>setForm({...form,planned_meters:e.target.value})} placeholder="5000"/></label><label className="field-card description-field"><span>{s.description}</span><textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder={s.descriptionPlaceholder}/></label></div><div className="session-sheet-actions"><button type="button" className="secondary-action" onClick={()=>setOpen(false)}>{t.common.cancel}</button><button className="primary" disabled={saving}>{saving?t.common.saving:s.save}</button></div></form>;
return <section><div className="section-toolbar"><div><span className="eyebrow">{s.trainings}</span><h2>{s.title}</h2><p>{s.intro}</p></div>{user.role==='coach'&&<button className="primary inline-action add-session-btn" onClick={()=>setOpen(true)}><Plus size={18}/>{s.new}</button>}</div>{error&&<div className="error">{error}</div>}{open&&user.role==='coach'&&<div className="session-modal"><div className="session-modal-backdrop" onClick={()=>setOpen(false)}/><div className="session-modal-panel">{sessionForm}</div></div>}<div className="session-list">{loading?<div className="card">{s.loading}</div>:events.length?events.map(ev=>{const response=responses[ev.id];const canAnswer=user.role==='athlete'&&finished(ev)&&!response;return <article className="card session-card" key={ev.id}><div className="session-icon"><Waves size={20}/></div><div className="session-body"><h3>{s.training}</h3><p><strong>{new Date(`${ev.event_date}T12:00:00`).toLocaleDateString(locale,{weekday:'long',day:'numeric',month:'long'})}</strong></p><p>{ev.start_time?.slice(0,5)}–{ev.end_time?.slice(0,5)}{ev.place?` · ${ev.place}`:''}</p>{ev.planned_meters&&<span className="pill">{ev.planned_meters} {s.plannedSuffix}</span>}{ev.description&&<p>{ev.description}</p>}{user.role==='athlete'&&response&&<div className="session-complete"><CheckCircle2 size={18}/><b>{s.valued}</b><span>Borg {response.borg}/10 · {response.meters} m</span></div>}{canAnswer&&answering!==ev.id&&<button className="primary response-button" onClick={()=>{setAnswering(ev.id);setAnswer({borg:5,meters:ev.planned_meters||'',comment:''})}}>{s.register}</button>}{canAnswer&&answering===ev.id&&<form className="training-response" onSubmit={e=>sendResponse(e,ev)}><label>{s.effort} <b>{answer.borg}/10 — {s.borg[answer.borg]}</b><input type="range" min="0" max="10" step="1" value={answer.borg} onChange={e=>setAnswer({...answer,borg:+e.target.value})}/><small>{s.legend}</small></label><label>{s.meters}<input type="number" min="0" required value={answer.meters} onChange={e=>setAnswer({...answer,meters:e.target.value})}/></label><label>{s.comment}<textarea rows="2" value={answer.comment} onChange={e=>setAnswer({...answer,comment:e.target.value})}/></label><div className="form-actions"><button type="button" onClick={()=>setAnswering(null)}>{t.common.cancel}</button><button className="primary" disabled={saving}>{saving?t.common.saving:s.submit}</button></div></form>}{user.role==='coach'&&<div className="coach-responses"><b>{(response||[]).length} {s.received}</b>{(response||[]).map(r=><span key={r.id}>Borg {r.borg}/10 · {r.meters} m{r.comment?` · ${r.comment}`:''}</span>)}</div>}</div></article>}):<div className="card empty-state">{s.none}</div>}</div></section>}
