import { useEffect,useState } from 'react';
import { CheckCircle2,RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useLanguage } from '../i18n';
const today=()=>new Date().toLocaleDateString('en-CA');
export default function WellnessPage({user}){const{t}=useLanguage();const w=t.wellness;const[entry,setEntry]=useState(null);const[entries,setEntries]=useState([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[form,setForm]=useState({sleep_quality:3,fatigue:3,soreness:3,stress:3,mood:3,sleep_hours:'',hrv_ms:'',comment:'',has_pain:false,pain_score:0,pain_note:''});
const load=async()=>{setLoading(true);setError('');if(user.role==='athlete'){const{data,error:e}=await supabase.from('wellness_entries').select('*').eq('athlete_id',user.id).eq('entry_date',today()).maybeSingle();if(e)setError(e.message);else setEntry(data)}else{const{data,error:e}=await supabase.from('wellness_entries').select('*, profiles!wellness_entries_athlete_id_fkey(full_name)').eq('entry_date',today()).order('created_at',{ascending:false});if(e){const fallback=await supabase.from('wellness_entries').select('*').eq('entry_date',today()).order('created_at',{ascending:false});if(fallback.error)setError(fallback.error.message);else setEntries(fallback.data||[])}else setEntries(data||[])}setLoading(false)};useEffect(()=>{load()},[user.id,user.role]);
const submit=async e=>{e.preventDefault();setSaving(true);setError('');const payload={athlete_id:user.id,entry_date:today(),sleep_quality:+form.sleep_quality,fatigue:+form.fatigue,soreness:+form.soreness,stress:+form.stress,mood:+form.mood,sleep_hours:+form.sleep_hours,hrv_ms:+form.hrv_ms,comment:form.comment.trim()||null,has_pain:form.has_pain,pain_score:form.has_pain?+form.pain_score:null,pain_note:form.has_pain?(form.pain_note.trim()||null):null};const{data,error:e2}=await supabase.from('wellness_entries').insert(payload).select().single();if(e2)setError(e2.code==='23505'?w.duplicate:e2.message);else setEntry(data);setSaving(false)};
if(loading)return <section className="card"><p>{t.common.loading}</p></section>;
if(user.role==='coach')return <><div className="section-toolbar"><div><span className="eyebrow">{w.today}</span><h2>{w.team}</h2><p>{entries.length} {w.responses}</p></div><button className="inline-action" onClick={load}><RefreshCw size={17}/>{t.common.update}</button></div>{error&&<div className="error">{error}</div>}<div className="wellness-list">{entries.length===0?<section className="card empty-state">{w.none}</section>:entries.map(x=><article className="card wellness-entry" key={x.id}><div><strong>{x.profiles?.full_name||w.athlete}</strong><span>HRV {x.hrv_ms} ms · {w.sleep} {x.sleep_hours} h</span></div><div className="wellness-values"><span>{w.sleep} <b>{x.sleep_quality}/5</b></span><span>{w.fatigue} <b>{x.fatigue}/5</b></span><span>{w.soreness} <b>{x.soreness}/5</b></span><span>{w.stress} <b>{x.stress}/5</b></span><span>{w.mood} <b>{x.mood}/5</b></span></div><div className={x.has_pain?'pain-alert':'pain-ok'}><b>{w.currentPain}: {x.has_pain?`${t.common.yes} · ${x.pain_score}/10`:t.common.no}</b>{x.has_pain&&x.pain_note&&<span>{x.pain_note}</span>}</div>{x.comment&&<p>{x.comment}</p>}</article>)}</div></>;
if(entry)return <section className="card wellness-done"><CheckCircle2 size={46}/><span className="eyebrow">{w.completed}</span><h2>{w.doneTitle}</h2><p>{w.doneText}</p><div className="wellness-summary"><span>HRV <b>{entry.hrv_ms} ms</b></span><span>{w.currentPain} <b>{entry.has_pain?`${entry.pain_score}/10`:t.common.no}</b></span></div></section>;
return <section className="card wellness-form"><span className="eyebrow">{w.daily}</span><h2>{w.how}</h2><p>{w.intro}</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit}><div className="wellness-scales">{w.scales.map(([key,label,legend])=><fieldset key={key}><legend>{label}</legend><small>{legend}</small><div className="scale-buttons">{[1,2,3,4,5].map(n=><label key={n} className={+form[key]===n?'selected':''}><input type="radio" name={key} checked={+form[key]===n} onChange={()=>setForm({...form,[key]:n})}/><span>{n}</span></label>)}</div></fieldset>)}</div><div className="form-grid"><label>{w.sleepHours}<input type="number" min="0" max="16" step="0.25" required value={form.sleep_hours} onChange={e=>setForm({...form,sleep_hours:e.target.value})}/></label><label>HRV (ms)<input type="number" min="1" max="500" required value={form.hrv_ms} onChange={e=>setForm({...form,hrv_ms:e.target.value})}/></label></div><fieldset className="pain-field"><legend>{w.painQuestion}</legend><div className="yes-no"><button type="button" className={!form.has_pain?'selected':''} onClick={()=>setForm({...form,has_pain:false,pain_score:0,pain_note:''})}>{t.common.no}</button><button type="button" className={form.has_pain?'selected danger':''} onClick={()=>setForm({...form,has_pain:true})}>{t.common.yes}</button></div>{form.has_pain&&<div className="pain-details"><label>{w.painIntensity}: <b>{form.pain_score}/10</b><input type="range" min="0" max="10" step="1" value={form.pain_score} onChange={e=>setForm({...form,pain_score:e.target.value})}/></label><label>{w.painNote}<textarea rows="3" value={form.pain_note} onChange={e=>setForm({...form,pain_note:e.target.value})} placeholder={w.painPlaceholder}/></label></div>}</fieldset><label>{w.comment}<textarea rows="3" value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})} placeholder={w.commentPlaceholder}/></label><div className="form-actions"><button className="primary" disabled={saving}>{saving?t.common.saving:w.submit}</button></div></form></section>}
