import { useEffect,useMemo,useState } from 'react';
import { Navigate,Route,Routes,useLocation,useNavigate } from 'react-router-dom';
import { Activity,CalendarDays,ClipboardCheck,Dumbbell,HeartPulse,Home,LogOut,Medal,Users } from 'lucide-react';
import { supabase } from './lib/supabase';
import { cteibLogo } from './cteibLogo';
import { useLanguage } from './i18n';
import CalendarPage from './pages/CalendarPage';
import SessionsPage from './pages/SessionsPage';
import WellnessPage from './pages/WellnessPage';
import AttendancePage from './pages/AttendancePage';
import CompetitionPage from './pages/CompetitionPage';
import DashboardPage from './pages/DashboardPage';
import AthletesPage from './pages/AthletesPage';
import LoadPage from './pages/LoadPage';

const switchWrap={display:'inline-flex',alignItems:'center',padding:3,background:'#f3e8ff',border:'1px solid #ddd6fe',borderRadius:999,gap:2};
const switchButton=active=>({border:0,background:active?'#6d28d9':'transparent',color:active?'#fff':'#7c3aed',fontWeight:800,fontSize:12,padding:'6px 9px',borderRadius:999,minWidth:38});
function LanguageSwitch(){const{language,setLanguage}=useLanguage();return <div style={switchWrap}><button type="button" style={switchButton(language==='es')} onClick={()=>setLanguage('es')}>ES</button><button type="button" style={switchButton(language==='ca')} onClick={()=>setLanguage('ca')}>CA</button></div>}
function navFor(role,t){const base=[["/",t.nav.home,Home],["/calendar",t.nav.calendar,CalendarDays],["/sessions",t.nav.sessions,Dumbbell]];return role==='coach'?[...base,["/load",t.nav.load,Activity],["/attendance",t.nav.attendance,ClipboardCheck],["/wellness",t.nav.wellness,HeartPulse],["/competitions",t.nav.competitions,Medal],["/athletes",t.nav.athletes,Users]]:[...base,["/wellness",t.nav.wellness,HeartPulse],["/competitions",t.nav.competitions,Medal]]}
function Login(){const{t}=useLanguage();const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const submit=async e=>{e.preventDefault();setError('');setLoading(true);const clean=username.trim().toLowerCase();const email=clean.includes('@')?clean:`${clean}@cteibnatacio.app`;const{error:signInError}=await supabase.auth.signInWithPassword({email,password});if(signInError)setError(t.login.error);setLoading(false)};return <main className="login-page" style={{position:'relative'}}><div style={{position:'fixed',top:14,right:14,zIndex:20}}><LanguageSwitch/></div><section className="login-brand"><img src={cteibLogo} alt="CTEIB Natació"/><span>Swim Performance Hub</span><h1>{t.login.program}</h1><p>{t.login.tagline}</p></section><section className="login-card"><div><span className="eyebrow">{t.login.access}</span><h2>{t.login.welcome}</h2><p>{t.login.subtitle}</p></div><form onSubmit={submit}><label>{t.login.user}<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" placeholder="entrenador" required/></label><label>{t.login.password}<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" required/></label>{error&&<div className="error">{error}</div>}<button className="primary" type="submit" disabled={loading}>{loading?t.login.entering:t.login.enter}</button></form></section></main>}
function Shell({user,onLogout}){const{t}=useLanguage();const nav=navFor(user.role,t);const location=useLocation();const navigate=useNavigate();const activeTitle=useMemo(()=>nav.find(([path])=>path===location.pathname)?.[1]||t.nav.home,[location.pathname,nav,t.nav.home]);return <div className="app-shell"><aside className="sidebar"><div className="brand-row"><img src={cteibLogo} alt="CTEIB Natació"/><div><strong>{t.login.program}</strong><span>Swim Performance Hub</span></div></div><nav>{nav.map(([path,label,Icon])=><button key={path} className={location.pathname===path?'active':''} onClick={()=>navigate(path)}><Icon size={19}/><span>{label}</span></button>)}</nav><div style={{marginTop:'auto',padding:'12px 14px 4px'}}><LanguageSwitch/></div><button className="logout" onClick={onLogout} style={{marginTop:4}}><LogOut size={18}/>{t.nav.logout}</button></aside><main className="main-content"><header><div><span className="eyebrow">{user.role==='coach'?t.role.coach:t.role.athlete}</span><h1>{activeTitle}</h1></div><div style={{display:'flex',alignItems:'center',gap:12}}><LanguageSwitch/><div className="user-pill">{user.name}</div></div></header><div className="page-content"><Routes><Route path="/" element={<DashboardPage user={user}/>}/><Route path="/calendar" element={<CalendarPage user={user}/>}/><Route path="/sessions" element={<SessionsPage user={user}/>}/><Route path="/load" element={user.role==='coach'?<LoadPage user={user}/>:<Navigate to="/" replace/>}/><Route path="/attendance" element={user.role==='coach'?<AttendancePage user={user}/>:<Navigate to="/" replace/>}/><Route path="/wellness" element={<WellnessPage user={user}/>}/><Route path="/competitions" element={<CompetitionPage user={user}/>}/><Route path="/athletes" element={user.role==='coach'?<AthletesPage user={user}/>:<Navigate to="/" replace/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></div></main><nav className="bottom-nav">{nav.map(([path,label,Icon])=><button key={path} className={location.pathname===path?'active':''} onClick={()=>navigate(path)}><Icon size={21}/><span>{label}</span></button>)}<button className="mobile-logout" type="button" onClick={onLogout}><LogOut size={21}/><span>{t.nav.close}</span></button></nav></div>}
export default function App(){const{t}=useLanguage();const[user,setUser]=useState(null);const[loading,setLoading]=useState(true);useEffect(()=>{let mounted=true;const loadProfile=async session=>{if(!session?.user){if(mounted){setUser(null);setLoading(false)}return}const{data:profile,error}=await supabase.from('profiles').select('id, full_name, role, active').eq('id',session.user.id).single();if(mounted){if(!error&&profile?.active)setUser({id:profile.id,name:profile.full_name||session.user.email,role:profile.role,email:session.user.email});else setUser(null);setLoading(false)}};supabase.auth.getSession().then(({data})=>loadProfile(data.session));const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>loadProfile(session));return()=>{mounted=false;listener.subscription.unsubscribe()}},[]);const logout=async()=>{await supabase.auth.signOut()};if(loading)return <main className="login-page"><section className="login-card"><h2>{t.common.loading}</h2></section></main>;return user?<Shell user={user} onLogout={logout}/>:<Login/>}
